### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by L6-hong** [liruihui/PointAugment#14]
@liruihui Hello, I found this problem in the process of running the code. Do you know why? I hope you can give me some suggestions, thank you.

**Comment by L6-hong** [comment]
@liruihui This is the result of my running command：
 checkpoints: log/pointnet_cls/20210114-1318
PARAMETER ...
Namespace(augment=False, batch_size=24, data_dir='ModelNet40_Folder', decay_rate=0.0001, epoch=250, epoch_per_save=5, learning_rate=0.001, learning_rate_a=0.001, log_dir='log/pointnet_cls/20210114-1318', lr_decay=0.5, model_name='pointnet', no_decay=False, noise_dim=1024, num_points=1024, optimizer='Adam', pretrain=None, restore=False, use_normal=False, y_rotated=True)
Load dataset ...
Traceback (most recent call last):
  File "train_PA.py", line 22, in <module>
    model.train()
  File "/floyd/home/Augment/model.py", line 64, in train
    trainDataLoader = DataLoader(ModelNetDataLoader(self.opts, partition='train'),
  File "/floyd/home/Common/ModelNetDataLoader.py", line 44, in __init__
    self.data, self.label = load_data(opts.data_dir,partition=partition)
  File "/floyd/home/Common/ModelNetDataLoader.py", line 26, in load_data
    all_data = np.concatenate(all_data, axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

**Comment by nickucas123** [comment]
Using format h5 datasets

**Comment by liruihui** [comment]
I think it may be about the dataset path.
